[#g3,reftext=G.3]
=== (G.3) Expected Benefits

ifdef::env-draft[]
TIP: _New processes, or improvement to existing processes, made possible by the project’s results. It presents the business benefits expected from the successful execution of the project. **This chapter is the core of the Goals book**, describing what the organization expects from the system. It ensures that the project remains focused: if at some stage it gets pushed in different directions, with “creeping featurism” threatening its integrity, a reminder about the original business goals stated in those chapters will help._  <<BM22>>
endif::[]

This application gamifies the experience of exercising, and in doing so the anticipated benefit is largely health oriented. By encouraging users to exercise outdoors, it allows them to enjoy their surroundings while helping them increase their fitness levels. Being able to exercise for free will help cut the cost of expensive gym memberships, fitness classes, and personal trainers. Additionally, the HRM integration serves to further support users in their goals to take care of their health. Furthermore, due to its close knit integration with local businesses and trails, there is an added benefit to them as well. Trail systems are likely to see more use, and by extension support, allowing them to continue to operate. The application also encourages users to explore nearby businesses, who are likely to benefit financially from the increased traffic within their stores.

.Goal model for ACME Run
image::models/benefits.svg[scale=70%,align="center"]